# Generated by Django 2.2 on 2019-02-22 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cup',
            old_name='manufactuerDate',
            new_name='manufacturerDate',
        ),
    ]
